// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-geopolitical-sentiment.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_geopolitical_sentiment_default = defineTool({
  name: "get_geopolitical_sentiment",
  title: "Get geopolitical sentiment",
  description: "Return the latest geopolitical tension score, severity, summary, and key events from QuantForecast. Educational context only, not investment advice.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("geopolitical_sentiment").select("tension_score, severity, summary, key_events, created_at").order("created_at", { ascending: false }).limit(1).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "No geopolitical sentiment available yet." }] };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/get-hot-stocks.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
var get_hot_stocks_default = defineTool2({
  name: "get_hot_stocks",
  title: "Get hot stocks screener",
  description: "Return QuantForecast's Hot Stocks screener candidates for a given risk profile (conservative, moderate, aggressive). Historical/educational \u2014 not a buy or sell recommendation.",
  inputSchema: {
    riskProfile: z.enum(["conservative", "moderate", "aggressive"]).describe("Risk profile to screen for.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ riskProfile }) => {
    const url = `${process.env.SUPABASE_URL}/functions/v1/hot-stocks`;
    const res = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        apikey: process.env.SUPABASE_PUBLISHABLE_KEY,
        Authorization: `Bearer ${process.env.SUPABASE_PUBLISHABLE_KEY}`
      },
      body: JSON.stringify({ riskProfile })
    });
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `hot-stocks error ${res.status}: ${await res.text()}` }],
        isError: true
      };
    }
    const json = await res.json();
    return {
      content: [{ type: "text", text: JSON.stringify(json) }],
      structuredContent: json
    };
  }
});

// src/lib/mcp/tools/get-stock-fundamentals.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_stock_fundamentals_default = defineTool3({
  name: "get_stock_fundamentals",
  title: "Get stock fundamentals",
  description: "Return cached fundamentals (sector, P/E, EPS, market cap, website) for a ticker symbol. Educational reference only, not investment advice.",
  inputSchema: {
    ticker: z2.string().trim().min(1).max(12).describe("Ticker symbol, e.g. AAPL.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ ticker }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const symbol = ticker.toUpperCase();
    const { data, error } = await supabase.from("stock_fundamentals").select("*").eq("ticker", symbol).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: `No fundamentals cached for ${symbol}.` }] };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/list-my-portfolios.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
var list_my_portfolios_default = defineTool4({
  name: "list_my_portfolios",
  title: "List my portfolio holdings",
  description: "Return the signed-in user's saved portfolio holdings from QuantForecast. Requires OAuth. Educational tracking only, not investment advice.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("portfolio_holdings").select("*").eq("user_id", ctx.getUserId());
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { holdings: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xsytjrvpqmbiedcmgebb";
var mcp_default = defineMcp({
  name: "quantforecast-mcp",
  title: "QuantForecast",
  version: "0.1.0",
  instructions: "Educational quantitative market analysis tools from QuantForecast. Provides geopolitical sentiment, cached stock fundamentals, the Hot Stocks screener, and (when signed in) the user's own tracked portfolio holdings. All outputs are for informational/educational purposes only and are NOT investment advice. QuantForecast is not a registered investment adviser.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_geopolitical_sentiment_default, get_stock_fundamentals_default, get_hot_stocks_default, list_my_portfolios_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
